# Generated by Django 5.1.2 on 2024-10-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_issue_component_issue_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='license_plate',
        ),
    ]
