# Generated by Django 5.1.2 on 2024-10-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_payment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
    ]
